Collections:
  - Name: Open Images Dataset
    Paper:
      URL: https://arxiv.org/abs/1811.00982
      Title: 'The Open Images Dataset V4: Unified image classification, object detection, and visual relationship detection at scale'
    README: configs/openimages/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.20.0/mmdet/datasets/openimages.py#L21
      Version: v2.20.0

Models:
  - Name: faster_rcnn_r50_fpn_32x2_1x_openimages
    In Collection: Open Images Dataset
    Config: configs/openimages/faster_rcnn_r50_fpn_32x2_1x_openimages.py
    Metadata:
      Training Memory (GB): 7.7
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: Open Images v6
        Metrics:
          box AP: 51.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/openimages/faster_rcnn_r50_fpn_32x2_1x_openimages/faster_rcnn_r50_fpn_32x2_1x_openimages_20211130_231159-e87ab7ce.pth

  - Name: retinanet_r50_fpn_32x2_1x_openimages
    In Collection: Open Images Dataset
    Config: configs/openimages/retinanet_r50_fpn_32x2_1x_openimages.py
    Metadata:
      Training Memory (GB): 6.6
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: Open Images v6
        Metrics:
          box AP: 61.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/openimages/retinanet_r50_fpn_32x2_1x_openimages/retinanet_r50_fpn_32x2_1x_openimages_20211223_071954-d2ae5462.pth

  - Name: ssd300_32x8_36e_openimages
    In Collection: Open Images Dataset
    Config: configs/openimages/ssd300_32x8_36e_openimages
    Metadata:
      Training Memory (GB): 10.8
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: Open Images v6
        Metrics:
          box AP: 35.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/openimages/ssd300_32x8_36e_openimages/ssd300_32x8_36e_openimages_20211224_000232-dce93846.pth

  - Name: faster_rcnn_r50_fpn_32x2_1x_openimages_challenge
    In Collection: Open Images Dataset
    Config: configs/openimages/faster_rcnn_r50_fpn_32x2_1x_openimages_challenge.py
    Metadata:
      Training Memory (GB): 7.7
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: Open Images Challenge 2019W
        Metrics:
          box AP: 54.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/openimages/faster_rcnn_r50_fpn_32x2_1x_openimages_challenge/faster_rcnn_r50_fpn_32x2_1x_openimages_challenge_20211229_071252-46380cde.pth
